server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Gzip compression
    gzip on;
    gzip_types text/css application/javascript application/json;

    # React Router : toutes les routes non trouvées → index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache des assets statiques (1 an)
    location ~* \.(js|css|png|jpg|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
