---
- name: Configuration du serveur de production AGROCAM S.A.
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:

    - name: Mettre a jour le cache apt
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Installer les dependances systeme
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - docker.io
          - python3-pip
        state: present

    - name: Demarrer et activer Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Ajouter ubuntu au groupe docker
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Installer Docker Compose v2
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Creer le dossier de deploiement
      file:
        path: /opt/digitrans-supply-chain
        state: directory
        mode: '0755'
        owner: ubuntu

    - name: Copier docker-compose.yml
      copy:
        src: ../docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml
        owner: ubuntu
        mode: '0644'

    - name: Lancer l application avec Docker Compose
      command: docker-compose -f /home/ubuntu/docker-compose.yml up -d --build
      become_user: ubuntu
