name: CI/CD Pipeline - Digitrans Supply Chain

on:
  push:
    branches:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Backend Tests
        run: echo "Tests backend OK"

  infrastructure:
    needs: test-backend
    runs-on: ubuntu-latest
    outputs:
      server_ip: "98.82.31.33"
    steps:
      - name: Skip Terraform Creation
        run: echo "Utilisation de l'instance AWS existante pour preserver les quotas."

  configure-server:
    needs: infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          name: id_rsa
          known_hosts: "placeholder"
          if_key_exists: replace

      - name: Scan Remote Host
        run: |
          SERVER_IP=${{ needs.infrastructure.outputs.server_ip }}
          # Creation explicite du dossier pour eviter le crash de ssh-keyscan
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan -H "$SERVER_IP" >> ~/.ssh/known_hosts

      - name: Run Ansible Playbook
        run: |
          SERVER_IP=${{ needs.infrastructure.outputs.server_ip }}
          sed -i "s/YOUR_EC2_IP/$SERVER_IP/g" ansible/inventory.ini
          
          ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook \
            -i ansible/inventory.ini \
            ansible/playbook.yml

  deploy-docker:
    needs: [infrastructure, configure-server]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          name: id_rsa
          known_hosts: "placeholder"
          if_key_exists: replace

      - name: Scan Remote Host
        run: |
          SERVER_IP=${{ needs.infrastructure.outputs.server_ip }}
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan -H "$SERVER_IP" >> ~/.ssh/known_hosts

      - name: Deploy Apps with Docker Compose
        env:
          SERVER_IP: ${{ needs.infrastructure.outputs.server_ip }}
        run: |
          scp docker-compose.yml ubuntu@$SERVER_IP:/home/ubuntu/docker-compose.yml
          ssh ubuntu@$SERVER_IP "
            cd /home/ubuntu &&
            docker compose pull &&
            docker compose up -d --remove-orphans
          "