name: CI/CD Pipeline - Digitrans Supply Chain

on:
  push:
    branches:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Backend Tests
        run: echo "Tests backend OK"

  infrastructure:
    needs: test-backend
    runs-on: ubuntu-latest
    outputs:
      server_ip: ${{ steps.tf_output.outputs.server_ip }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0
          terraform_wrapper: false

      - name: Manage SSH Keypair on AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws ec2 delete-key-pair --key-name "digitrans-deploy-key-v2" || true
          aws ec2 import-key-pair --key-name "digitrans-deploy-key-v2" --public-key-material "${{ secrets.SSH_PUBLIC_KEY }}"

      - name: Terraform Init
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: terraform init

      - name: Terraform Apply
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: terraform apply -auto-approve

      - name: Get Server IP
        id: tf_output
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          IP=$(terraform output -raw server_public_ip)
          echo "server_ip=$IP" >> $GITHUB_OUTPUT

  configure-server:
    needs: infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ needs.infrastructure.outputs.server_ip }} >> ~/.ssh/known_hosts

      - name: Run Ansible Playbook
        run: |
          SERVER_IP=${{ needs.infrastructure.outputs.server_ip }}
          sed -i "s/YOUR_EC2_IP/$SERVER_IP/g" ansible/inventory.ini
          ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i ansible/inventory.ini ansible/playbook.yml --private-key=~/.ssh/id_rsa
